<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PingByDaylight.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include=" Ardalis.Result" Version="10.1.0" />
  </ItemGroup>

</Project>
